defaults: &defaults
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2
  working_directory: ~/ember-octicons

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --no-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint_hbs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint HBS
          command: yarn run lint:hbs

  lint_js:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS
          command: yarn run lint:js

  test_lts_3_8:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/ember-octicons/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-lts-3.8 --skip-cleanup=true

  test_lts_3_12:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/ember-octicons/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-lts-3.12 --skip-cleanup=true

  test_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/ember-octicons/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-release --skip-cleanup=true

  test_beta:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/ember-octicons/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: ember try:one ember-beta --skip-cleanup=true

workflows:
  version: 2
  test_matrix:
    jobs:
      - install_dependencies
      - lint_hbs:
          requires:
            - install_dependencies
      - lint_js:
          requires:
            - install_dependencies
      - test_lts_3_8:
          requires:
            - install_dependencies
      - test_lts_3_12:
          requires:
            - install_dependencies
      - test_release:
          requires:
            - install_dependencies
      - test_beta:
          requires:
            - install_dependencies
